[font]
size = 14.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ZedMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ZedMono Nerd Font"
style = "Italic"

[font.normal]
family = "ZedMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
startup_mode = "Windowed"
opacity = 0.9

[window.padding]
x = 36
y = 36

[shell]
program = "wsl"

