version: "3"
networks:
  gitea:
    external: false
  caddy:
services:
  gitea_server:
    image: gitea/gitea:nightly
    container_name: gitea
    environment:
      - USER_UID=1026
      - USER_GID=100
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=redacted
      - GITEA__database__NAME=redacted
      - GITEA__database__USER=redacted
      - GITEA__database__PASSWD=redacted
    restart: always
    networks:
      - gitea
      - caddy
    volumes:
      - /volume1/docker/gitea/data:/data
      - /volume1/docker/gitea/timezone:/etc/timezone:ro
      - /volume1/docker/gitea/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22" # change ports accordantly
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    security_opt:
     - no-new-privileges:true
    ports:
     - 80:80 # cahnge ports accordantly
     - 443:443
    volumes:
     - /volume1/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
     - /volume1/docker/caddy/site:/srv
     - /volume1/docker/caddy/caddy_data:/data
     - /volume1/docker/caddy/caddy_config:/config
    networks:
     - caddy
volumes:
  caddy_data:
   external: true
  caddy_config: