# Catppuccino theme scheme for Alacritty

[colors.primary]
background = '#1E1E2E'
foreground = '#D6D6D6'

[colors.cursor]
text = '#1E1E2E'
cursor = '#D9D9D9'

[colors.normal]
black = '#181A1F'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#ABB2BF'

[colors.bright]
black = '#5C6370'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#F7F7F7'

[colors.dim]
black = '#5C6370'
red = '#74423F'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#6E4962'
cyan = '#5C8482'
white = '#828282'

[font]
size = 20.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 36
y = 36
